name: Auth Service CI/CD

on:
  push:
    paths:
      - 'auth_service/**'
    branches: [develop, main]
  pull_request:
    paths:
      - 'auth_service/**'
    branches: [develop, main]

jobs:
  auth-ci:
    name: Build, Test, Lint, Docker
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 📦 Install dependencies
        run: |
          cd auth_service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black ruff pytest pytest-cov

      - name: ✅ Run unit tests with coverage
        run: |
          cd auth_service
          pytest --cov=. --cov-report=term-missing

      - name: 🧼 Run Black (format check)
        run: |
          cd auth_service
          black . --check

      - name: 🔍 Run Ruff (lint check)
        run: |
          cd auth_service
          ruff .

      - name: 🐳 Docker Build
        run: |
          cd auth_service
          docker build -t ${{ github.repository }}:auth-${{ github.sha }} .

      - name: ☁️ Login to Docker Hub
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🐳 Push Docker Image
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: |
          docker tag ${{ github.repository }}:auth-${{ github.sha }} truongcaovan/auth_service:latest
          truongcaovan/auth_service:latest
