version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql+asyncpg://test:password@postgres:5432/auth_service_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache

volumes:
  postgres_data: