global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
        send_resolved: true

  - name: 'email-notifications'
    email_configs:
      - to: 'admin@foodandfast.com'
        from: 'alertmanager@foodandfast.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'alertmanager@foodandfast.com'
        auth_password: 'your-email-password'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance'] 