version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    container_name: food_fast_postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - food_fast_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Cache
  redis:
    image: redis:7-alpine
    container_name: food_fast_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - food_fast_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: food_fast_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - food_fast_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway
  api_gateway:
    build:
      context: ../api_gateway
      dockerfile: Dockerfile
    container_name: food_fast_api_gateway
    ports:
      - "8000:8000"
    env_file:
      - ../api_gateway/.env
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - food_fast_network
    restart: unless-stopped

  # Auth Service
  auth_service:
    build:
      context: ../auth_service
      dockerfile: Dockerfile
    container_name: food_fast_auth_service
    ports:
      - "8001:8001"
    env_file:
      - ../auth_service/.env
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8001
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/auth_service_db
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - food_fast_network
    restart: unless-stopped

  # User Service
  user_service:
    build:
      context: ../user_service
      dockerfile: Dockerfile
    container_name: food_fast_user_service
    ports:
      - "8002:8002"
    env_file:
      - ../user_service/.env
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8002
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/user_service_db
      - REDIS_URL=redis://redis:6379/2
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - food_fast_network
    restart: unless-stopped

  # Product Service
  product_service:
    build:
      context: ../product_service
      dockerfile: Dockerfile
    container_name: food_fast_product_service
    ports:
      - "8003:8003"
    env_file:
      - ../product_service/.env
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8003
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/product_service_db
      - REDIS_URL=redis://redis:6379/3
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - food_fast_network
    restart: unless-stopped

  # Order Service
  order_service:
    build:
      context: ../order_service
      dockerfile: Dockerfile
    container_name: food_fast_order_service
    ports:
      - "8004:8004"
    env_file:
      - ../order_service/.env
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8004
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/order_service_db
      - REDIS_URL=redis://redis:6379/4
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - food_fast_network
    restart: unless-stopped

  # Payment Service
  payment_service:
    build:
      context: ../payment_service
      dockerfile: Dockerfile
    container_name: food_fast_payment_service
    ports:
      - "8005:8005"
    env_file:
      - ../payment_service/.env
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8005
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/payment_service_db
      - REDIS_URL=redis://redis:6379/5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - food_fast_network
    restart: unless-stopped

  # Notification Service
  notification_service:
    build:
      context: ../notification_service
      dockerfile: Dockerfile
    container_name: food_fast_notification_service
    ports:
      - "8006:8006"
    env_file:
      - ../notification_service/.env
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8006
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/notification_service_db
      - REDIS_URL=redis://redis:6379/6
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - food_fast_network
    restart: unless-stopped

  # Analytics Service
  analytics_service:
    build:
      context: ../analytics_service
      dockerfile: Dockerfile
    container_name: food_fast_analytics_service
    ports:
      - "8007:8007"
    env_file:
      - ../analytics_service/.env
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8007
      - DATABASE_URL=postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/analytics_service_db
      - REDIS_URL=redis://redis:6379/7
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - food_fast_network
    restart: unless-stopped

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: food_fast_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - food_fast_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: food_fast_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - food_fast_network
    restart: unless-stopped

  # PostgreSQL Exporter for database metrics
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: food_fast_postgres_exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - food_fast_network
    restart: unless-stopped

  # Redis Exporter for cache metrics
  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: food_fast_redis_exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis://redis:6379"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - food_fast_network
    restart: unless-stopped

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: food_fast_node_exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - food_fast_network
    restart: unless-stopped

  # Alertmanager for alerting
  alertmanager:
    image: prom/alertmanager:latest
    container_name: food_fast_alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - food_fast_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
  prometheus_data:
  grafana_data:
  alertmanager_data:

networks:
  food_fast_network:
    driver: bridge
