name: Develop CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [user_service, product_service, order_service, payment_service, auth_service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd ${{ matrix.service }}
          pytest || echo "No tests found in ${{ matrix.service }}"

      - name: Check formatting (black)
        run: |
          cd ${{ matrix.service }}
          black . --check

  # Optional Docker Build Step (if needed)
  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker compose -f infrastructure/docker-compose.yml build
